### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by amv** [sainikumara/chat#1]
It is customary for server projects to define a "start script" in the `package.ini`, so that I can do this:

```
 $ npm install
 $ npm start
```

There are two ways to achieve this, documented here:

https://docs.npmjs.com/cli/start

**Comment by tstarck** [comment]
As a side note, Antti really means `package.json`.

**Comment by sainikumara** [comment]
Pull request #3 fixes this by renaming index.js to server.js.
